### ISSUE TITLE
 Failed opening required '../config.php'

### ISSUE THREAD

**Issue by wumiolabisi** [ernestovi/ups#10]
Impossible d'inclure la page config.php dans la nouvelle page que je tente de créer dans Moodle

Voici le code exact présent dans ma page PHP : 
<?php

require('../config.php');
require_once($CFG->dirroot . '/user/editlib.php');

//$PAGE->set_context(get_system_context());
$PAGE->set_pagelayout('standard');
$PAGE->set_title("Your title");
$PAGE->set_heading("Blank page");
$PAGE->set_url($CFG->wwwroot.'/blank_page.php');

echo $OUTPUT->header();
echo "Hello World";
echo $OUTPUT->footer();
?>

J'ai l'erreur suivante : 

Warning: require(../config.php): failed to open stream: No such file or directory in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\projects\univPop\moodle\customscripts\tutoring\blank_page.php on line 3

Fatal error: require(): Failed opening required '../config.php' (include_path='.;C:\php\pear') in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\projects\univPop\moodle\customscripts\tutoring\blank_page.php on line 3

HELP !

**Comment by noelno** [comment]
Si ta page est dans \customscripts\tutoring alors il faut remonter de deux répertoires et pas d'un seul si je ne m'abuse ? Donc ça devrait plutôt être require('../../config.php');

**Comment by samszo** [comment]
je confirme
"failed to open stream: No such file or directory"
est une erreur classique qui vient d'une mauvaise adresse de l'include
