### ISSUE TITLE
Récupérer du contenu dynamique hors du répertoire Moodle

### ISSUE THREAD

**Issue by noelno** [ernestovi/ups#11]
Bonjour,

J'essaie de récupérer du contenu dynamique de Moodle, en particulier l'id de l'utilisateur courant, son nom, son prénom et son numéro de session, pour le réinjecter dans l'entête de SPIP. 
Je peux afficher ces données dans une nouvelle page dans le répertoire moodle, mais je n'ai trouvé aucun moyen pour que Spip accède à ces données. Auriez-vous une solution ?

**Comment by samszo** [comment]
il suffit de passer les informations dans l'url et de les récupérer dans le squelette : http://www.spip.net/fr_article4014.html
