### ISSUE TITLE
str_replace() ne fonctionne pas

### ISSUE THREAD

**Issue by noelno** [ernestovi/ups#12]
Bonjour,

J'ai crée un filtre qui reçoit en paramètre la langue courante de la page et son url, et qui retourne dans Spip un menu des langues disponibles - tout en ajoutant une classe "selected" à la langue courante. 

Pour ajouter les liens permettant de changer de langue j'ai utilisé la variable #SELF concaténée avec "lang=deuxpremiereslettresdelalangue". Le problème c'est que #SELF retourne l'URL de la page courante avec tous ses attributs, par exemple path/to/spip.php?rubrique16&lang=en&var_mode=calcul. Ce qui signifie que si je passe du français à l'arabe à l'anglais puis encore à l'arabe, l'url va ressembler à ça : path/to/spip.php?rubrique16&lang=fr&lang=ar&lang=en&lang=ar.
J'ai donc ajouté à ma fonction des instructions censées effacer "&lang=deuxpremiereslettresdelalangue" mais cela n'a aucun effet.

Voici ce à quoi ressemble le filtre : 

``` php
function filtre_menu_langue($languecourante, $pagecourante){

    $lang = array('fr','en','ar');
    $buttons = '<span id="langue">';

    $pagecourante = str_replace('&lang=fr', '', $pagecourante);
    $pagecourante = str_replace('&lang=en', '', $pagecourante);
    $pagecourante = str_replace('&lang=ar', '', $pagecourante);

    for($i = 0; $i < count($lang); $i++){
        if ($languecourante == $lang[$i]){
            $class = ' class="selected"';
        }
        else{
            $class = '';
        }
        $buttons .= '<a href="'.$pagecourante.'&lang='.$lang[$i].'"'.$class.'>'.ucfirst($lang[$i]).'</a>';
    }

    $buttons .= '</span>';
    return $buttons;
} 
```

Et ce filtre est appelé ainsi dans le squelette : 
`[(#LANG|menu_langue{#SELF})]`

Seules les instructions str_replace ne font pas le travail. Est-ce que vous voyez pourquoi ?

**Comment by noelno** [comment]
Selon la documentation officielle SPIP, #SELF est supposée retourner l'url sans les variables en question : [http://www.spip.net/fr_article4574.html](http://www.spip.net/fr_article4574.html)

**Comment by samszo** [comment]
Je ne pense qu'il soit nécessaire de développer ton propre filtre : http://contrib.spip.net/Menu-de-langues-sous-forme-de-liens
voici un exemple : http://gapai.univ-paris8.fr/open-edition/Accueil
l'inclusion du menu dans le squelette : https://github.com/samszo/open-edition/blob/master/squelettes/inclure/header.html#L28
Il faudrait l'adresse de la page qui pose problème sur le serveur http://cdnl-2015.hymedia.univ-paris8.fr/univPop/

sinon ton problème de replace est lié au caractère "&"  
il faudrait plutôt passer par cette fonction : http://php.net/manual/fr/function.parse-url.php

**Comment by noelno** [comment]
J'ai regardé la fonction parse-url, elle me permet de récupérer la première partie de l'url proprement, mais l'identifiant de la page à afficher et le &lang= sont contenus dans le même champ du tableau, à savoir $array['query'], et je me retrouve avec le même problème, je ne peux pas séparer le &lang=fr de ?rubrique16 ou ?article3.
Du coup j'ai installé le plugin Menu de langues sous forme de lien et ça fonctionne.
Merci !
