### ISSUE TITLE
Cahier de conception : copyright

### ISSUE THREAD

**Issue by noelno** [ernestovi/ups#4]
Bonjour,

Doit-on spécifier un copyright dans le cahier de conception ? Si oui est-ce qu'il existe un copyright type pour les productions universitaires (cahier de conception, mémoires etc...) ?

**Comment by samszo** [comment]
il n'y a pas de copyright mais plutôt un copyleft comme creative commons cf. http://creativecommons.fr/

**Comment by wumiolabisi** [comment]
Bonsoir,

On en a parlé avec Claude et le choix d'une licence tous droits réservés pour le cahier de conception a été retenu
