### ISSUE TITLE
[webapp] allow-navigation ouvre la page dans un navigateur externe

### ISSUE THREAD

**Issue by noelno** [ernestovi/ups#8]
Bonjour,

Je m'occupe du développement de la webapp qui doit encapsuler l'application.
Selon le cours de développement mobile, il faut ajouter au fichier config.xml le plugin whitelist, et ajouter une entrée allow-navigation vers le site dans lequel on souhaite naviguer via l'application, pour l'instant l'url cdnl-2015.hymedia.univ-paris8.fr/univPop.

Problème : lorsque l'application tente d'accéder à cette url, elle demande dans quel navigateur ouvrir cette page, alors que l'objectif est de naviguer dans le site à travers l'application.

Comment résoudre ce problème ?
[upsmobile0.zip](https://github.com/ernestovi/ups/files/276364/upsmobile0.zip)

**Comment by wumiolabisi** [comment]
Techniquement, l'application encapsule une url. Qui dit url, dit ressource sur internet (et non sur le mobile). Et pour naviguer sur internet il faut forcément un navigateur web. Je suis entrain d'installer ce qu'il faut sur ma machine pour tester. Mais à mon avis, le comportement que tu as signalé est normal.

**Comment by noelno** [comment]
Notre professeur de développement mobile nous a donné la solution : en fait le problème venait du slash final en bout d'url dans la whitelist. Rajouter un /index.php dans l'url de redirection résout le problème : `<meta http-equiv="refresh" content="0; URL=http://cdnl-2015.hymedia.univ-paris8.fr/univPop/index.php">`
